name: install-sql-server-action
description: Install and run SQL Server in a container for use in a GitHub Actions workflow
inputs:
  connection-string-env-var:
    description: The name of the environment variable to fill with the SQL Server connection string.
    required: true
  catalog:
    description: Name of the initial database (catalog) to create.
    required: false
    default: nservicebus
  collation:
    description: The collation to use for the SQL Server database.
    required: false
    default: "SQL_Latin1_General_CP1_CS_AS"
  sqlserver-version:
    description: The SQL Server major version to use.
    required: false
    default: "2022"
  extra-params:
    description: Extra parameters to append to the end of the connection string.
    required: false
  enable-full-text-search:
    description: Enable SQL Server Full-Text Search installation.
    required: false
    default: "false"
  enable-distributed-transactions:
    description: Enable SQL Server distributed transactions (MSDTC) in the container.
    required: false
    default: "false"
runs:
  using: node24
  main: dist/index.mjs
  post: dist/index.mjs
